### ISSUE TITLE
Create_student are not linked to the student_class table 

### ISSUE THREAD

**Issue by alkalinan** [TheSoftwareFactory/DLearnHelsinki-backend#52]
When creating a new student, the student is not added to the table Student_Classes. This cause the student to not show up when we are requesting classes, groups, etc..

**Comment by WaDelma** [comment]
If creating new student succeeds, then it should add try to add the student to the `Student_Classes` table. So adding the student to the `Student_Classes` is failing for some reason.

I noticed that it doesn't ensure that `class_id` match between class and groups, but I don't think the problem is with that.
