### ISSUE TITLE
Passwords are stored as plain text in the db

### ISSUE THREAD

**Issue by mihassin** [TheSoftwareFactory/DLearnHelsinki-backend#91]
Quick fix to the slowness issue. If a proper tokenizer is configured, the encryption would not cause slowness.

**Comment by esaaksvu** [comment]
Fixed in commit (https://github.com/TheSoftwareFactory/DLearnHelsinki-backend/commit/3983d31ba4cf8817f3c48bf644052a03e05d372e) and added to master branch in (https://github.com/TheSoftwareFactory/DLearnHelsinki-backend/pull/95). 

Passwords are now encrypted with BCrypt(12) when stored in database. When accessing page, raw password and encoded hash are cached with sha256 encryption to give faster access. Hashes are removed from cache after 5 minutes of idling.
